import type { ClientData, User } from "./types";

// SAMPLE DATA. Every number here is illustrative and clearly labeled as sample
// in the UI. Real Signal reads from admin-vetted Google Sheet workbooks
// (Results / Calls / Emails / LinkedIn / Active Contacts), then live webhooks.
// The YetiConnect meeting rows are drawn from a real StudioGTM cold-call tracker.

const LAST_UPDATED = "Jul 1, 2026 · 8:04 AM";

export const CLIENTS: Record<string, ClientData> = {
  yeticonnect: {
    client: {
      id: "yeticonnect",
      name: "YetiConnect",
      slug: "yeticonnect",
      industry: "AI conversation platform (med spa + automotive)",
      accountOwner: "Blake Harber",
      sdrs: ["Derek"],
      status: "active",
      startDate: "2026-05-12",
      drive: {
        data: "https://drive.google.com/drive/folders/1TeZnZ6TIfz4OD-GVK9OXO5XNld6hhJED",
        channel: "#",
        messaging: "#",
        agreements: "#",
        working: "#",
      },
    },
    results: {
      closedWon: 48000,
      newPipeline: 212000,
      meetingsHeld: 14,
      meetingsScheduled: 18,
      holdRate: 78,
      closedWonDelta: 48000,
      meetingsHeldDelta: 6,
      pipelineOpps: 18,
    },
    meetings: [
      {
        id: "y1",
        name: "Desiree O.",
        company: "Texas Dermatology and Laser Specialists",
        title: "Marketing",
        campaign: "MedSpa – Derek",
        stage: "demo_set",
        dateScheduled: "2026-06-30",
        attended: null,
        rep: "Derek",
        value: 18000,
        note: "Desiree expressed interest — it aligns with their needs. Derek scheduled a Zoom demo for the 30th; she'll invite the med-spa manager and supervisor who work directly with inbound leads.",
        phone: "(210) 707-9050",
        email: "desiree@texasdls.com",
        transcript: "https://app.nooks.in/",
        featured: true,
      },
      {
        id: "y2",
        name: "Noah England",
        company: "Piedmont Plastic Surgery & Dermatology",
        title: "COO",
        campaign: "MedSpa – Derek",
        stage: "follow_up",
        dateScheduled: "2026-07-02",
        attended: null,
        rep: "Derek",
        value: 24000,
        note: "Noah (COO) was interested but heading into a conference. Agreed to a Wednesday-afternoon follow-up to go deeper on unifying marketing and sales.",
        phone: "(303) 250-0325",
        email: "nengland@ppsd.com",
        linkedin: "https://www.linkedin.com/in/noahengland/",
        transcript: "https://app.nooks.in/",
        featured: true,
      },
      {
        id: "y3",
        name: "Justin Kohll",
        company: "Preventative Medical Clinic",
        campaign: "MedSpa – Derek",
        stage: "follow_up",
        dateScheduled: "2026-07-01",
        attended: null,
        rep: "Derek",
        value: 12000,
        note: "Justin is out of the country, back next week. Derek scheduled a follow-up call for Wednesday to walk through converting inbound leads.",
        phone: "(402) 306-6503",
        email: "jkohll@kohllspmc.com",
        linkedin: "https://www.linkedin.com/in/justin-kohll-2a2b87b/",
        transcript: "https://app.nooks.in/",
      },
      {
        id: "y4",
        name: "Larry Dobbs",
        company: "Classic Cruisers",
        campaign: "Automotive – Derek",
        stage: "nurture",
        dateScheduled: "2026-07-22",
        attended: null,
        rep: "Derek",
        value: 9000,
        note: "Larry is setting up a new business; asked to reconnect after the 4th. Confirmed best number for follow-up. Not using text-message marketing today.",
        phone: "(706) 244-4259",
        linkedin: "https://www.linkedin.com/in/larry-dobbs-2a516788",
        transcript: "https://app.nooks.in/",
      },
      {
        id: "y5",
        name: "Marcus Web",
        company: "Radiance Aesthetics",
        title: "Owner",
        campaign: "MedSpa – Derek",
        stage: "won",
        dateScheduled: "2026-06-18",
        attended: true,
        rep: "Derek",
        value: 26000,
        note: "Demo held and closed. Owner loved the AI call recording; signed a 12-month agreement.",
        featured: true,
      },
      {
        id: "y6",
        name: "Priya Anand",
        company: "Lakeshore Dermatology",
        title: "Practice Manager",
        campaign: "MedSpa – Derek",
        stage: "held",
        dateScheduled: "2026-06-24",
        attended: true,
        rep: "Derek",
        value: 22000,
        note: "Strong first meeting. Evaluating against one other vendor; follow-up demo with the physician group scheduled.",
      },
    ],
    phone: { dials: 2940, connects: 241, conversations: 96, meetings: 18 },
    email: { sent: 4120, opens: 1730, replies: 168, positiveReplies: 41 },
    linkedin: { contacts: 610, connects: 232, replies: 74, positiveReplies: 19 },
    replies: [
      {
        id: "r1",
        name: "Desiree O.",
        company: "Texas Dermatology",
        channel: "email",
        sentiment: "positive",
        message: "This looks really interesting — send me the calendar invite and I'll loop in our med-spa manager.",
        date: "2026-06-23",
      },
      {
        id: "r2",
        name: "Karen Blount",
        company: "Elite Skin Co",
        channel: "linkedin",
        sentiment: "positive",
        message: "We've been looking for exactly this. Who's the right person to talk pricing?",
        date: "2026-06-25",
      },
      {
        id: "r3",
        name: "Tom Reilly",
        company: "AutoNation West",
        channel: "email",
        sentiment: "neutral",
        message: "Not right now but check back in Q4 — we're mid-migration.",
        date: "2026-06-26",
      },
    ],
    activeLeads: {
      attempting: 612,
      unworked: 388,
      target: 700,
      statuses: [
        { label: "Attempting to contact", count: 612 },
        { label: "Callback set", count: 84 },
        { label: "Nurture", count: 121 },
        { label: "Not interested", count: 203 },
        { label: "Bad data", count: 57 },
        { label: "Yet to be worked", count: 388 },
      ],
    },
    benchmarks: [
      { label: "Email deliverability", value: 96, unit: "%", benchmark: 90, status: "good", higherIsBetter: true, note: "Inbox placement is healthy — the pipes are clear." },
      { label: "Reply rate", value: 4.1, unit: "%", benchmark: 1.8, status: "good", higherIsBetter: true, note: "2.3x the industry average. The med-spa message is landing." },
      { label: "Dial-to-connect", value: 8.2, unit: "%", benchmark: 10, status: "warn", higherIsBetter: true, note: "Slightly below benchmark — testing new call windows." },
      { label: "Meeting hold rate", value: 78, unit: "%", benchmark: 82, status: "warn", higherIsBetter: true, note: "A confirm-call sequence should close the gap." },
    ],
    campaigns: [
      { id: "c1", name: "MedSpa – Derek", channel: "multi" },
      { id: "c2", name: "Automotive – Derek", channel: "phone" },
    ],
    projects: [
      {
        id: "p1",
        name: "MedSpa segment list build",
        owner: "Brett",
        due: "2026-07-03",
        stages: [
          { label: "Scoped", state: "done" },
          { label: "Data pull", state: "done" },
          { label: "Enrichment", state: "active" },
          { label: "QA", state: "todo" },
          { label: "Live", state: "todo" },
        ],
      },
      {
        id: "p2",
        name: "Automotive email sequence",
        owner: "Blake",
        due: "2026-07-08",
        stages: [
          { label: "Scoped", state: "done" },
          { label: "Drafted", state: "active" },
          { label: "Reviewed", state: "todo" },
          { label: "Warmed", state: "todo" },
          { label: "Live", state: "todo" },
        ],
      },
    ],
    unitEconomics: {
      meetingsPerMonth: 18,
      showRate: 78,
      oppToWin: 22,
      avgDealValue: 24000,
      programCost: 6500,
    },
    insight:
      "Your outbound is booking meetings at 2.3× the industry reply rate — and the med-spa message is doing the heavy lifting. Where we're leaking: hold rate (78% vs 82% benchmark), worth a confirm-call tweak.",
    lastUpdated: LAST_UPDATED,
  },

  pontelabor: {
    client: {
      id: "pontelabor",
      name: "Ponte Labor",
      slug: "pontelabor",
      industry: "Labor & staffing",
      accountOwner: "Clay Tirrell",
      sdrs: ["Maria"],
      status: "onboarding",
      startDate: "2026-07-07",
      drive: {
        data: "https://drive.google.com/drive/folders/1TeZnZ6TIfz4OD-GVK9OXO5XNld6hhJED",
        channel: "https://drive.google.com/drive/folders/1KaGo2XufNJ7xjMJSurTEhPG6dTyxlSJY",
        messaging: "https://drive.google.com/drive/folders/1LNZX7vgSq402mzUSlQ7Ck3xUsbkdOKeD",
        agreements: "https://drive.google.com/drive/folders/1AjLk7wP-oTxE6lls464_TojcPko5e975",
        working: "https://drive.google.com/drive/folders/1pnVFAKp24IOJnR0vPQduOS4gZFmB0KdM",
      },
    },
    results: {
      closedWon: 0,
      newPipeline: 0,
      meetingsHeld: 0,
      meetingsScheduled: 0,
      holdRate: 0,
      closedWonDelta: 0,
      meetingsHeldDelta: 0,
      pipelineOpps: 0,
    },
    meetings: [],
    phone: { dials: 0, connects: 0, conversations: 0, meetings: 0 },
    email: { sent: 0, opens: 0, replies: 0, positiveReplies: 0 },
    linkedin: { contacts: 0, connects: 0, replies: 0, positiveReplies: 0 },
    replies: [],
    activeLeads: {
      attempting: 0,
      unworked: 0,
      target: 600,
      statuses: [{ label: "Yet to be worked", count: 0 }],
    },
    benchmarks: [],
    campaigns: [],
    projects: [
      {
        id: "pl1",
        name: "Onboarding & data packet",
        owner: "Clay Tirrell",
        due: "2026-07-07",
        stages: [
          { label: "Intake", state: "done" },
          { label: "Drive setup", state: "done" },
          { label: "ICP + segments", state: "active" },
          { label: "Scripts", state: "todo" },
          { label: "Launch", state: "todo" },
        ],
      },
    ],
    unitEconomics: {
      meetingsPerMonth: 15,
      showRate: 75,
      oppToWin: 20,
      avgDealValue: 18000,
      programCost: 6000,
    },
    insight:
      "Ponte Labor launches next week. Onboarding is on track — the data packet and Drive are set up, ICP and segments are in progress.",
    lastUpdated: LAST_UPDATED,
  },

  northwind: {
    client: {
      id: "northwind",
      name: "Northwind Freight",
      slug: "northwind",
      industry: "Logistics & 3PL",
      accountOwner: "Brett",
      sdrs: ["Andre", "Priya"],
      status: "active",
      startDate: "2026-03-01",
      drive: { data: "#", channel: "#", messaging: "#", agreements: "#", working: "#" },
    },
    results: {
      closedWon: 96000,
      newPipeline: 340000,
      meetingsHeld: 22,
      meetingsScheduled: 27,
      holdRate: 84,
      closedWonDelta: 32000,
      meetingsHeldDelta: 4,
      pipelineOpps: 24,
    },
    meetings: [
      {
        id: "n1",
        name: "Gary Holt",
        company: "Summit Distribution",
        title: "VP Ops",
        campaign: "3PL – Andre",
        stage: "won",
        dateScheduled: "2026-06-20",
        attended: true,
        rep: "Andre",
        value: 54000,
        note: "Closed. Consolidating three carriers; Northwind won on lane coverage and the dedicated-rep model.",
        featured: true,
      },
      {
        id: "n2",
        name: "Lena Ortiz",
        company: "Cascade Foods",
        title: "Supply Chain Director",
        campaign: "3PL – Priya",
        stage: "held",
        dateScheduled: "2026-06-27",
        attended: true,
        rep: "Priya",
        value: 41000,
        note: "Great fit on cold-chain lanes. Requesting a pilot on the Pacific NW routes.",
      },
    ],
    phone: { dials: 3810, connects: 352, conversations: 141, meetings: 27 },
    email: { sent: 5230, opens: 2140, replies: 214, positiveReplies: 58 },
    linkedin: { contacts: 820, connects: 341, replies: 96, positiveReplies: 28 },
    replies: [
      {
        id: "nr1",
        name: "Lena Ortiz",
        company: "Cascade Foods",
        channel: "email",
        sentiment: "positive",
        message: "Yes — let's get a pilot scoped for the NW routes. Send times.",
        date: "2026-06-26",
      },
    ],
    activeLeads: {
      attempting: 940,
      unworked: 210,
      target: 900,
      statuses: [
        { label: "Attempting to contact", count: 940 },
        { label: "Callback set", count: 132 },
        { label: "Nurture", count: 188 },
        { label: "Not interested", count: 260 },
        { label: "Bad data", count: 74 },
        { label: "Yet to be worked", count: 210 },
      ],
    },
    benchmarks: [
      { label: "Email deliverability", value: 92, unit: "%", benchmark: 90, status: "good", higherIsBetter: true, note: "Healthy inbox placement across domains." },
      { label: "Reply rate", value: 4.1, unit: "%", benchmark: 1.8, status: "good", higherIsBetter: true, note: "Strong — logistics pain points resonate." },
      { label: "Dial-to-connect", value: 9.2, unit: "%", benchmark: 10, status: "warn", higherIsBetter: true, note: "Close to benchmark; testing morning blocks." },
      { label: "Meeting hold rate", value: 84, unit: "%", benchmark: 82, status: "good", higherIsBetter: true, note: "Above benchmark — confirm-call cadence is working." },
    ],
    campaigns: [
      { id: "nc1", name: "3PL – Andre", channel: "multi" },
      { id: "nc2", name: "3PL – Priya", channel: "multi" },
    ],
    projects: [
      {
        id: "np1",
        name: "Cold-chain vertical expansion",
        owner: "Brett",
        due: "2026-07-11",
        stages: [
          { label: "Scoped", state: "done" },
          { label: "Data pull", state: "done" },
          { label: "Enrichment", state: "done" },
          { label: "QA", state: "active" },
          { label: "Live", state: "todo" },
        ],
      },
    ],
    unitEconomics: {
      meetingsPerMonth: 27,
      showRate: 84,
      oppToWin: 26,
      avgDealValue: 45000,
      programCost: 8500,
    },
    insight:
      "Northwind is your strongest account this month — $340k new pipeline and an above-benchmark 84% hold rate. Cold-chain lanes are the emerging wedge worth doubling down on.",
    lastUpdated: LAST_UPDATED,
  },

  cedarvine: {
    client: {
      id: "cedarvine",
      name: "Cedar & Vine Consulting",
      slug: "cedarvine",
      industry: "Boutique management consulting",
      accountOwner: "Clay Tirrell",
      sdrs: ["Andre"],
      status: "at_risk",
      startDate: "2026-04-15",
      drive: { data: "#", channel: "#", messaging: "#", agreements: "#", working: "#" },
    },
    results: {
      closedWon: 0,
      newPipeline: 54000,
      meetingsHeld: 4,
      meetingsScheduled: 9,
      holdRate: 44,
      closedWonDelta: 0,
      meetingsHeldDelta: -2,
      pipelineOpps: 5,
    },
    meetings: [
      {
        id: "cv1",
        name: "Dana Whitfield",
        company: "Harbor Point Partners",
        title: "Managing Partner",
        campaign: "PE-backed ops – Andre",
        stage: "held",
        dateScheduled: "2026-06-19",
        attended: true,
        rep: "Andre",
        value: 30000,
        note: "Interested in the ops-diligence offering but pushed timing to fall. Needs a clearer ROI story.",
      },
    ],
    phone: { dials: 1420, connects: 96, conversations: 31, meetings: 9 },
    email: { sent: 2010, opens: 690, replies: 44, positiveReplies: 7 },
    linkedin: { contacts: 300, connects: 88, replies: 18, positiveReplies: 3 },
    replies: [
      {
        id: "cvr1",
        name: "Dana Whitfield",
        company: "Harbor Point Partners",
        channel: "email",
        sentiment: "neutral",
        message: "Revisit in the fall — bandwidth is tight until then.",
        date: "2026-06-20",
      },
    ],
    activeLeads: {
      attempting: 240,
      unworked: 460,
      target: 500,
      statuses: [
        { label: "Attempting to contact", count: 240 },
        { label: "Callback set", count: 22 },
        { label: "Nurture", count: 64 },
        { label: "Not interested", count: 118 },
        { label: "Bad data", count: 96 },
        { label: "Yet to be worked", count: 460 },
      ],
    },
    benchmarks: [
      { label: "Email deliverability", value: 81, unit: "%", benchmark: 90, status: "bad", higherIsBetter: true, note: "Below benchmark — domain warmup and list hygiene needed." },
      { label: "Reply rate", value: 2.2, unit: "%", benchmark: 1.8, status: "good", higherIsBetter: true, note: "Slightly above average despite deliverability drag." },
      { label: "Dial-to-connect", value: 6.8, unit: "%", benchmark: 10, status: "bad", higherIsBetter: true, note: "Low — data quality (16% bad numbers) is the culprit." },
      { label: "Meeting hold rate", value: 44, unit: "%", benchmark: 82, status: "bad", higherIsBetter: true, note: "Well below benchmark. No-shows are the top risk to this account." },
    ],
    campaigns: [{ id: "cvc1", name: "PE-backed ops – Andre", channel: "multi" }],
    projects: [
      {
        id: "cvp1",
        name: "List rebuild + deliverability fix",
        owner: "Andre",
        due: "2026-07-05",
        stages: [
          { label: "Scoped", state: "done" },
          { label: "Data pull", state: "active" },
          { label: "Enrichment", state: "todo" },
          { label: "QA", state: "todo" },
          { label: "Live", state: "todo" },
        ],
        note: "At-risk recovery plan",
      },
    ],
    unitEconomics: {
      meetingsPerMonth: 9,
      showRate: 44,
      oppToWin: 18,
      avgDealValue: 30000,
      programCost: 6500,
    },
    insight:
      "Cedar & Vine needs attention. Deliverability (81%) and bad data (16% of numbers) are throttling output, and a 44% hold rate is dragging results. Recovery plan: list rebuild + domain warmup, in progress.",
    lastUpdated: LAST_UPDATED,
  },
};

export const CLIENT_ORDER = ["yeticonnect", "northwind", "pontelabor", "cedarvine"];

// Demo users — one per role, to show how access scope changes the same view.
export const USERS: Record<string, User> = {
  owner: {
    id: "owner",
    name: "Clay Tirrell",
    email: "clay@studiogtm.co",
    role: "owner",
    clientAccess: "all",
    seesBilling: true,
  },
  sdr: {
    id: "sdr",
    name: "Derek (SDR)",
    email: "derek@studiogtm.co",
    role: "sdr",
    clientAccess: ["yeticonnect"],
    seesBilling: false,
  },
  client: {
    id: "client",
    name: "YetiConnect Founder",
    email: "founder@yeticonnect.com",
    role: "client",
    clientAccess: ["yeticonnect"],
    seesBilling: true,
  },
  client_team: {
    id: "client_team",
    name: "YetiConnect Sales Lead",
    email: "sales@yeticonnect.com",
    role: "client_team",
    clientAccess: ["yeticonnect"],
    seesBilling: false,
  },
};

export function getClientData(id: string): ClientData | undefined {
  return CLIENTS[id];
}

export function accessibleClientIds(user: User): string[] {
  if (user.clientAccess === "all") return CLIENT_ORDER;
  return CLIENT_ORDER.filter((id) => (user.clientAccess as string[]).includes(id));
}
