"use client";

import { useEffect, useMemo, useState } from "react";
import { Phone, Contact, Mail, Radio, FileText, ChevronRight } from "lucide-react";
import { Card, SectionTitle, EmptyState, Pill } from "@/components/ui";
import { LiveFeed } from "@/components/live-feed";
import { num, ratePct } from "@/lib/format";
import { monthLabel, monthKey } from "@/lib/history";
import {
  CALLS_MONTHLY,
  EMAIL_CAMPAIGNS,
  FLAX_CALL_LISTS,
  FLAX_CALL_TOTALS,
  FLAX_LINKEDIN_CAMPAIGNS,
  FLAX_LINKEDIN_TOTALS,
  YETI_CALL_LOG,
  YETI_CALL_WEEKS,
  type MonthlyCalls,
} from "@/lib/historical";
import { clientMeta } from "@/lib/clients";

export function FunnelTile({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div className="rounded-[10px] border border-border bg-surface-2 px-3.5 py-3">
      <p className="text-[11px] uppercase tracking-wide text-ink-3">{label}</p>
      <p className="serif tabular mt-0.5 text-[22px] leading-none text-ink">{value}</p>
      {sub && <p className="mt-1 text-[11.5px] text-ink-2">{sub}</p>}
    </div>
  );
}

/** Nooks-style stat block: a row of counts, then a row of conversion rates. */
export function CallStats({
  dials,
  callbacks,
  connects,
  conversations,
  meetings,
}: {
  dials: number;
  callbacks: number | null;
  connects: number | null;
  conversations: number | null;
  meetings: number;
}) {
  return (
    <div className="space-y-2">
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">
        <FunnelTile label="Dials" value={num(dials)} />
        <FunnelTile label="Callbacks" value={callbacks != null ? num(callbacks) : "—"} />
        <FunnelTile label="Connects" value={connects != null ? num(connects) : "—"} />
        <FunnelTile label="Conversations" value={conversations != null ? num(conversations) : "—"} />
        <FunnelTile label="Meetings" value={num(meetings)} />
      </div>
      {connects != null && conversations != null && (
        <div className="grid grid-cols-3 gap-2">
          <FunnelTile label="Dial to connect" value={ratePct(connects, dials)} />
          <FunnelTile label="Connect to conversation" value={ratePct(conversations, connects)} />
          <FunnelTile label="Conversation to meeting" value={ratePct(meetings, conversations)} />
        </div>
      )}
    </div>
  );
}

// ---------- Call log (per-person drill-in) ----------

interface LogRow {
  ts: number; // for sorting; 0 when unparseable
  when: string;
  client: string;
  name: string;
  company: string;
  rep: string;
  outcome: string;
  tone: "good" | "warn" | "bad" | "neutral";
  /** URL (Orum/Nooks link) or inline transcript text */
  transcript: string;
  recording: string;
  note: string;
  objection: string;
  list: string;
}

const isUrl = (s: string) => /^https?:\/\//.test(s);

const YETI_OUTCOME_TONE: Record<string, "good" | "warn" | "bad" | "neutral"> = {
  "Meeting booked": "good",
  "Email follow-up requested": "good",
  "Elevator pitch rejected": "bad",
};

function parseWhen(s: string): { ts: number; when: string } {
  if (!s) return { ts: 0, when: "—" };
  const d = new Date(s.includes("T") ? s : s.replace(" ", "T"));
  if (isNaN(d.getTime())) return { ts: 0, when: s.slice(0, 16) || "—" };
  return {
    ts: d.getTime(),
    when: d.toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }),
  };
}

interface ApiCall {
  prospect: string;
  company: string;
  disposition: string;
  tone: "good" | "warn" | "bad" | "neutral";
  rep: string;
  at: string;
  transcript: string;
  recording: string;
  note: string;
  objection: string;
}

// Per-call history from the Orum export (public/data/call-log.json,
// generated by scripts/gen_call_log.py). Fetched once and cached.
interface ExportCall {
  c: string;
  at: string;
  name: string;
  co: string;
  rep: string;
  out: string;
  tone: "good" | "warn" | "bad" | "neutral";
  rec: string;
  list: string;
  tr?: string; // inline transcript text
  note?: string; // AI-generated call notes
  obj?: string; // objections
}

let exportLogCache: Promise<ExportCall[]> | null = null;
function fetchExportLog(): Promise<ExportCall[]> {
  if (!exportLogCache) {
    exportLogCache = fetch("/data/call-log.json")
      .then((r) => (r.ok ? r.json() : []))
      .catch(() => []);
  }
  return exportLogCache;
}

export function CallLog({ clientIds }: { clientIds: string[] }) {
  const [liveCalls, setLiveCalls] = useState<LogRow[]>([]);
  const [exportRows, setExportRows] = useState<LogRow[]>([]);
  const [repFilter, setRepFilter] = useState("");
  const [outcomeFilter, setOutcomeFilter] = useState("");
  const [clientFilter, setClientFilter] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [showAll, setShowAll] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);
  const clientsKey = clientIds.join(",");
  const showClient = clientIds.length > 1;

  useEffect(() => {
    let on = true;
    const ids = clientsKey ? clientsKey.split(",") : [];
    Promise.all(
      ids.map((id) =>
        fetch(`/api/calls?client=${id}`)
          .then((r) => r.json())
          .then((d) => [id, d.ok && Array.isArray(d.calls) ? (d.calls as ApiCall[]) : []] as const)
          .catch(() => [id, [] as ApiCall[]] as const)
      )
    ).then((pairs) => {
      if (!on) return;
      setLiveCalls(
        pairs.flatMap(([id, calls]) =>
          calls.map((c) => {
            const { ts, when } = parseWhen(c.at);
            return {
              ts,
              when,
              client: id,
              name: c.prospect || "—",
              company: c.company || "",
              rep: c.rep || "—",
              outcome: c.disposition || "—",
              tone: c.tone ?? "neutral",
              transcript: c.transcript || "",
              recording: c.recording || "",
              note: c.note || "",
              objection: c.objection || "",
              list: "",
            };
          })
        )
      );
    });
    return () => { on = false; };
  }, [clientsKey]);

  useEffect(() => {
    let on = true;
    const ids = new Set(clientsKey.split(","));
    fetchExportLog().then((all) => {
      if (!on) return;
      setExportRows(
        all
          .filter((c) => ids.has(c.c))
          .map((c) => {
            const { ts, when } = parseWhen(c.at);
            return {
              ts,
              when,
              client: c.c,
              name: c.name,
              company: c.co,
              rep: c.rep,
              outcome: c.out,
              tone: c.tone,
              transcript: c.tr ?? "",
              recording: c.rec,
              note: c.note ?? "",
              objection: c.obj ?? "",
              list: c.list,
            };
          })
      );
    });
    return () => { on = false; };
  }, [clientsKey]);

  const histRows = useMemo<LogRow[]>(() => {
    if (!clientsKey.split(",").includes("yeticonnect")) return [];
    return YETI_CALL_LOG.map((c) => {
      const { ts, when } = parseWhen(c.calledAt);
      return {
        ts,
        when,
        client: "yeticonnect",
        name: c.name,
        company: c.company,
        rep: c.rep || "—",
        outcome: c.outcome,
        tone: YETI_OUTCOME_TONE[c.outcome] ?? "neutral",
        transcript: c.transcript,
        recording: "",
        note: "",
        objection: "",
        list: c.list,
      };
    });
  }, [clientsKey]);

  const rows = useMemo(
    () => [...liveCalls, ...exportRows, ...histRows].sort((a, b) => b.ts - a.ts),
    [liveCalls, exportRows, histRows]
  );
  const reps = useMemo(() => [...new Set(rows.map((r) => r.rep).filter((r) => r !== "—"))].sort(), [rows]);
  const outcomes = useMemo(() => [...new Set(rows.map((r) => r.outcome).filter((o) => o !== "—"))].sort(), [rows]);
  const logClients = useMemo(() => [...new Set(rows.map((r) => r.client))], [rows]);

  const filtered = rows.filter((r) => {
    if (clientFilter && r.client !== clientFilter) return false;
    if (repFilter && r.rep !== repFilter) return false;
    if (outcomeFilter && r.outcome !== outcomeFilter) return false;
    if (fromDate && r.ts && r.ts < new Date(fromDate + "T00:00:00").getTime()) return false;
    if (toDate && r.ts && r.ts > new Date(toDate + "T23:59:59").getTime()) return false;
    return true;
  });
  const visible = showAll ? filtered : filtered.slice(0, 25);

  if (rows.length === 0) return null;

  const selectCls = "rounded-[8px] border border-border bg-surface px-2 py-1 text-[12.5px] text-ink";

  return (
    <div className="mt-5 border-t border-border pt-4">
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <p className="mr-auto text-[13px] font-medium text-ink">
          Call log <span className="text-ink-3">· {num(filtered.length)} of {num(rows.length)} calls</span>
        </p>
        {showClient && (
          <select value={clientFilter} onChange={(e) => setClientFilter(e.target.value)} className={selectCls}>
            <option value="">All clients</option>
            {logClients.map((c) => (
              <option key={c} value={c}>{clientMeta(c)?.name ?? c}</option>
            ))}
          </select>
        )}
        <select value={repFilter} onChange={(e) => setRepFilter(e.target.value)} className={selectCls}>
          <option value="">All SDRs</option>
          {reps.map((r) => (
            <option key={r} value={r}>{r}</option>
          ))}
        </select>
        <select value={outcomeFilter} onChange={(e) => setOutcomeFilter(e.target.value)} className={selectCls}>
          <option value="">All outcomes</option>
          {outcomes.map((o) => (
            <option key={o} value={o}>{o}</option>
          ))}
        </select>
        <input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} className={selectCls} aria-label="From date" />
        <span className="text-[12px] text-ink-3">to</span>
        <input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} className={selectCls} aria-label="To date" />
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[640px] text-[12.5px]">
          <thead>
            <tr className="border-b border-border text-left text-[11px] uppercase tracking-wide text-ink-3">
              <th className="py-1.5 font-medium">Date · time</th>
              {showClient && <th className="py-1.5 font-medium">Client</th>}
              <th className="py-1.5 font-medium">Contact</th>
              <th className="py-1.5 font-medium">SDR</th>
              <th className="py-1.5 font-medium">Outcome</th>
              <th className="py-1.5 text-right font-medium">Transcript / recording</th>
            </tr>
          </thead>
          <tbody>
            {visible.map((r, i) => {
              const hasDetail = !!(r.transcript || r.note || r.objection || r.recording || r.list);
              const open = expanded === i;
              return (
                <FragmentRow
                  key={i}
                  r={r}
                  open={open}
                  hasDetail={hasDetail}
                  showClient={showClient}
                  onToggle={() => setExpanded(open ? null : i)}
                />
              );
            })}
          </tbody>
        </table>
      </div>
      {filtered.length > visible.length && (
        <button onClick={() => setShowAll(true)} className="mt-2 text-[12.5px] text-gold hover:opacity-80">
          Show all {num(filtered.length)} calls
        </button>
      )}
    </div>
  );
}

/** One call row + its expandable detail (labels, AI note, objections, transcript). */
function FragmentRow({
  r,
  open,
  hasDetail,
  showClient,
  onToggle,
}: {
  r: LogRow;
  open: boolean;
  hasDetail: boolean;
  showClient: boolean;
  onToggle: () => void;
}) {
  return (
    <>
      <tr
        onClick={hasDetail ? onToggle : undefined}
        className={`border-b border-border/60 last:border-0 ${hasDetail ? "cursor-pointer hover:bg-surface-2" : ""}`}
      >
        <td className="tabular whitespace-nowrap py-2 text-ink-2">
          <span className="inline-flex items-center gap-1.5">
            {hasDetail && (
              <ChevronRight size={13} className={`text-ink-3 transition-transform ${open ? "rotate-90" : ""}`} />
            )}
            {r.when}
          </span>
        </td>
        {showClient && <td className="whitespace-nowrap py-2 text-ink-2">{clientMeta(r.client)?.name ?? r.client}</td>}
        <td className="py-2">
          <span className="block font-medium text-ink">{r.name}</span>
          {r.company && <span className="block text-[11.5px] text-ink-3">{r.company}</span>}
        </td>
        <td className="whitespace-nowrap py-2 text-ink">{r.rep}</td>
        <td className="py-2"><Pill tone={r.tone}>{r.outcome}</Pill></td>
        <td className="py-2 text-right" onClick={(e) => e.stopPropagation()}>
          {isUrl(r.transcript) || r.recording ? (
            <a
              href={isUrl(r.transcript) ? r.transcript : r.recording}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 text-gold hover:opacity-80"
            >
              <FileText size={13} /> open
            </a>
          ) : r.transcript ? (
            <button onClick={onToggle} className="text-gold hover:opacity-80">view</button>
          ) : (
            <span className="text-ink-3">—</span>
          )}
        </td>
      </tr>
      {open && (
        <tr className="border-b border-border/60">
          <td colSpan={showClient ? 6 : 5} className="bg-surface-2/60 px-3 py-3">
            <div className="space-y-2.5 text-[12.5px]">
              {r.list && (
                <p className="text-ink-2"><span className="font-medium text-ink">List:</span> {r.list}</p>
              )}
              {r.objection && (
                <p className="text-ink-2"><span className="font-medium text-ink">Objections:</span> {r.objection}</p>
              )}
              {r.note && (
                <div>
                  <p className="mb-0.5 font-medium text-ink">Call notes</p>
                  <p className="whitespace-pre-wrap text-ink-2">{r.note}</p>
                </div>
              )}
              {r.transcript && !isUrl(r.transcript) && (
                <div>
                  <p className="mb-0.5 font-medium text-ink">Transcript</p>
                  <p className="max-h-48 overflow-y-auto whitespace-pre-wrap rounded-[8px] border border-border bg-surface p-2.5 text-ink-2">
                    {r.transcript}
                  </p>
                </div>
              )}
              <div className="flex gap-4">
                {isUrl(r.transcript) && (
                  <a href={r.transcript} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-gold hover:opacity-80">
                    <FileText size={13} /> Full transcript
                  </a>
                )}
                {r.recording && (
                  <a href={r.recording} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-gold hover:opacity-80">
                    <Radio size={13} /> Recording
                  </a>
                )}
              </div>
            </div>
          </td>
        </tr>
      )}
    </>
  );
}

// ---------- Calls panel (single-client scope) ----------

export function CallsPanel({ clientId, months }: { clientId: string; months: string[] }) {
  const [live, setLive] = useState<MonthlyCalls | null>(null);
  const currentMonth = monthKey(new Date());

  useEffect(() => {
    let on = true;
    fetch(`/api/calls?client=${clientId}&range=this_month`)
      .then((r) => r.json())
      .then((d) => {
        if (on && d.ok && d.metrics && d.metrics.dials > 0) {
          setLive({
            clientId,
            month: currentMonth,
            dials: d.metrics.dials,
            callbacks: null,
            connects: d.metrics.connects,
            conversations: d.metrics.conversations,
            meetings: d.metrics.meetings,
          });
        }
      })
      .catch(() => {});
    return () => { on = false; };
  }, [clientId, currentMonth]);

  const monthSet = new Set(months);
  const rows = CALLS_MONTHLY.filter((r) => r.clientId === clientId && monthSet.has(r.month));
  const all = live && monthSet.has(live.month) ? [...rows, live] : rows;

  // YetiConnect runs TWO dialers (confirmed by Clay): Brandon's team on Orum
  // (per-call export with real funnel flags, in CALLS_MONTHLY) and Derek on
  // Nooks (tracker weekly rollups, own outcome taxonomy). Official dial
  // volume = both summed; the funnel rates come from the Orum side only.
  if (clientId === "yeticonnect") {
    const weeks = YETI_CALL_WEEKS.filter((w) => monthSet.has(w.weekStart.slice(0, 7)));
    if (weeks.length === 0 && all.length === 0) {
      return (
        <Card className="p-5">
          <SectionTitle icon={<Phone size={16} />} title="Calls" />
          <EmptyState title="No calling data in this range" body="YetiConnect's calling history covers June onward — widen the date range to see it." />
          <CallLog clientIds={[clientId]} />
        </Card>
      );
    }
    const nooks = {
      dials: weeks.reduce((a, w) => a + w.callsMade, 0),
      meetings: weeks.reduce((a, w) => a + w.meetingsBooked, 0),
    };
    const orum = all.reduce(
      (a, r) => ({
        dials: a.dials + r.dials,
        connects: a.connects + r.connects,
        conversations: a.conversations + r.conversations,
        meetings: a.meetings + r.meetings,
      }),
      { dials: 0, connects: 0, conversations: 0, meetings: 0 }
    );
    const outcomeTotals = new Map<string, number>();
    for (const w of weeks) for (const o of w.outcomes) outcomeTotals.set(o.label, (outcomeTotals.get(o.label) ?? 0) + o.count);
    return (
      <Card className="p-5">
        <SectionTitle
          icon={<Phone size={16} />}
          title="Calls"
          right={<span className="text-[12px] text-ink-3">two dialers · Orum + Nooks summed</span>}
        />
        <CallStats
          dials={nooks.dials + orum.dials}
          callbacks={null}
          connects={null}
          conversations={null}
          meetings={nooks.meetings + orum.meetings}
        />
        <p className="mt-2 text-[11.5px] text-ink-3">
          Connect/conversation rates aren't shown at the combined level — the Nooks tracker doesn't report them. The Orum
          side's full funnel is below; Nooks weeks count toward the month they start in.
        </p>

        <p className="mb-1 mt-4 text-[11px] uppercase tracking-wide text-ink-3">Orum dialer (per-call export)</p>
        <CallStats dials={orum.dials} callbacks={null} connects={orum.connects} conversations={orum.conversations} meetings={orum.meetings} />
        {all.length > 1 && (
          <table className="mt-2 w-full text-[12.5px]">
            <tbody>
              {all.map((r) => (
                <tr key={r.month} className="border-b border-border/60 last:border-0">
                  <td className="py-1.5 text-ink">{monthLabel(r.month)}</td>
                  <td className="tabular py-1.5 text-right text-ink-2">{num(r.dials)} dials</td>
                  <td className="tabular py-1.5 text-right text-ink-2">{num(r.connects)} connects</td>
                  <td className="tabular py-1.5 text-right text-ink-2">{num(r.conversations)} conversations</td>
                  <td className="tabular py-1.5 text-right text-ink-2">{num(r.meetings)} mtgs</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}

        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <div>
            <p className="mb-1 text-[11px] uppercase tracking-wide text-ink-3">Nooks dialer (Derek) — by week</p>
            <table className="w-full text-[12.5px]">
              <tbody>
                {weeks.map((w) => (
                  <tr key={w.weekLabel} className="border-b border-border/60 last:border-0">
                    <td className="py-1.5 text-ink">{w.weekLabel}</td>
                    <td className="tabular py-1.5 text-right text-ink-2">{num(w.callsMade)} calls</td>
                    <td className="tabular py-1.5 text-right text-ink-2">{num(w.meetingsBooked)} mtgs</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div>
            <p className="mb-1 text-[11px] uppercase tracking-wide text-ink-3">Nooks outcomes in range</p>
            <table className="w-full text-[12.5px]">
              <tbody>
                {[...outcomeTotals.entries()].sort((a, b) => b[1] - a[1]).map(([label, count]) => (
                  <tr key={label} className="border-b border-border/60 last:border-0">
                    <td className="py-1.5 text-ink">{label}</td>
                    <td className="tabular py-1.5 text-right text-ink-2">{num(count)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
        <CallLog clientIds={[clientId]} />
      </Card>
    );
  }

  // Flax: all-time export only (not month-filterable).
  if (all.length === 0 && clientId === "flax") {
    const t = FLAX_CALL_TOTALS;
    return (
      <Card className="p-5">
        <SectionTitle
          icon={<Phone size={16} />}
          title="Calls"
          right={<span className="text-[12px] text-ink-3">all-time · dial export (not month-filterable)</span>}
        />
        <CallStats dials={t.dials} callbacks={null} connects={t.connects} conversations={t.conversations} meetings={t.meetings} />
        <p className="mb-1 mt-4 text-[11px] uppercase tracking-wide text-ink-3">Top lists (all-time)</p>
        <table className="w-full text-[12.5px]">
          <tbody>
            {FLAX_CALL_LISTS.slice(0, 5).map((l) => (
              <tr key={l.segment + l.list} className="border-b border-border/60 last:border-0">
                <td className="max-w-[280px] truncate py-1.5 text-ink">{l.list}</td>
                <td className="tabular py-1.5 text-right text-ink-2">{num(l.dials)} dials</td>
                <td className="tabular py-1.5 text-right text-ink-2">{num(l.connects)} connects</td>
                <td className="tabular py-1.5 text-right text-ink-2">{num(l.meetings)} mtgs</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    );
  }

  if (all.length === 0) {
    return (
      <Card className="p-5">
        <SectionTitle icon={<Phone size={16} />} title="Calls" />
        <EmptyState
          title="No calling data in this range"
          body="No calling history was imported for this client in the selected months, and no live dialer events have arrived. Live tracking starts as soon as a dialer connector fires."
        />
        <CallLog clientIds={[clientId]} />
      </Card>
    );
  }

  const t = all.reduce(
    (a, r) => ({
      dials: a.dials + r.dials,
      callbacks: r.callbacks != null ? (a.callbacks ?? 0) + r.callbacks : a.callbacks,
      connects: a.connects + r.connects,
      conversations: a.conversations + r.conversations,
      meetings: a.meetings + r.meetings,
    }),
    { dials: 0, callbacks: null as number | null, connects: 0, conversations: 0, meetings: 0 }
  );

  return (
    <Card className="p-5">
      <SectionTitle
        icon={<Phone size={16} />}
        title="Calls"
        right={
          <span className="text-[12px] text-ink-3">
            {live ? "history + live (Orum)" : "historical import"}
          </span>
        }
      />
      <CallStats dials={t.dials} callbacks={t.callbacks} connects={t.connects} conversations={t.conversations} meetings={t.meetings} />

      {all.length > 1 && (
        <table className="mt-4 w-full text-[12.5px]">
          <thead>
            <tr className="border-b border-border text-left text-[11px] uppercase tracking-wide text-ink-3">
              <th className="py-1.5 font-medium">Month</th>
              <th className="py-1.5 text-right font-medium">Dials</th>
              <th className="py-1.5 text-right font-medium">Callbacks</th>
              <th className="py-1.5 text-right font-medium">Connects</th>
              <th className="py-1.5 text-right font-medium">Conversations</th>
              <th className="py-1.5 text-right font-medium">Meetings</th>
            </tr>
          </thead>
          <tbody>
            {all.map((r) => (
              <tr key={r.month} className="border-b border-border/60 last:border-0">
                <td className="tabular py-1.5 text-ink">
                  {monthLabel(r.month)}
                  {live && r.month === live.month && <Pill tone="gold"> live</Pill>}
                </td>
                <td className="tabular py-1.5 text-right text-ink">{num(r.dials)}</td>
                <td className="tabular py-1.5 text-right text-ink">{r.callbacks != null ? num(r.callbacks) : "—"}</td>
                <td className="tabular py-1.5 text-right text-ink">{num(r.connects)}</td>
                <td className="tabular py-1.5 text-right text-ink">{num(r.conversations)}</td>
                <td className="tabular py-1.5 text-right text-ink">{num(r.meetings)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <CallLog clientIds={[clientId]} />
    </Card>
  );
}

export function LinkedInPanel({ clientId }: { clientId: string }) {
  if (clientId !== "flax") {
    return (
      <Card className="p-5">
        <SectionTitle icon={<Contact size={16} />} title="LinkedIn" />
        <EmptyState
          title="Awaiting data"
          body="No LinkedIn history has been imported for this client. Connect LGM or HeyReach webhooks (Settings → Connectors) to track it live."
        />
      </Card>
    );
  }
  const t = FLAX_LINKEDIN_TOTALS;
  return (
    <Card className="p-5">
      <SectionTitle
        icon={<Contact size={16} />}
        title="LinkedIn"
        right={<span className="text-[12px] text-ink-3">LGM report · {t.campaignsLaunched} launched campaigns</span>}
      />
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        <FunnelTile label="Contacted" value={num(t.contacted)} />
        <FunnelTile label="Replies" value={num(t.replies)} sub={`${ratePct(t.replies, t.contacted)} blended reply rate`} />
        <FunnelTile label="Won" value={num(t.won)} sub="interested + booked" />
        <FunnelTile label="Audiences" value={num(t.audiences)} />
      </div>
      <p className="mb-1 mt-4 text-[11px] uppercase tracking-wide text-ink-3">Top campaigns by replies</p>
      <table className="w-full text-[12.5px]">
        <tbody>
          {FLAX_LINKEDIN_CAMPAIGNS.slice(0, 5).map((c) => (
            <tr key={c.campaign} className="border-b border-border/60 last:border-0">
              <td className="max-w-[300px] truncate py-1.5 text-ink">{c.campaign}</td>
              <td className="tabular py-1.5 text-right text-ink-2">{num(c.contacted)} contacted</td>
              <td className="tabular py-1.5 text-right text-ink-2">{num(c.replies)} replies</td>
              <td className="tabular py-1.5 text-right text-ink-2">{ratePct(c.replies, c.contacted)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </Card>
  );
}

export function EmailPanel({ clientId }: { clientId: string }) {
  const campaigns = EMAIL_CAMPAIGNS.filter((c) => c.clientId === clientId);
  if (campaigns.length === 0) {
    return (
      <Card className="p-5">
        <SectionTitle icon={<Mail size={16} />} title="Email" />
        <EmptyState
          title="Awaiting data"
          body="No email history has been imported for this client. Connect Smartlead or Instantly webhooks (Settings → Connectors) to track it live."
        />
      </Card>
    );
  }
  const totals = campaigns.reduce(
    (a, c) => ({ contacts: a.contacts + c.contacts, sent: a.sent + c.sent, replies: a.replies + c.replies }),
    { contacts: 0, sent: 0, replies: 0 }
  );
  return (
    <Card className="p-5">
      <SectionTitle icon={<Mail size={16} />} title="Email" right={<span className="text-[12px] text-ink-3">by campaign · historical import</span>} />
      <table className="w-full text-[12.5px]">
        <thead>
          <tr className="border-b border-border text-left text-[11px] uppercase tracking-wide text-ink-3">
            <th className="py-1.5 font-medium">Campaign</th>
            <th className="py-1.5 text-right font-medium">Contacts</th>
            <th className="py-1.5 text-right font-medium">Sent</th>
            <th className="py-1.5 text-right font-medium">Replies</th>
            <th className="py-1.5 text-right font-medium">Reply rate</th>
          </tr>
        </thead>
        <tbody>
          {campaigns.map((c) => (
            <tr key={c.campaign} className="border-b border-border/60">
              <td className="py-1.5 text-ink">{c.campaign}</td>
              <td className="tabular py-1.5 text-right text-ink">{num(c.contacts)}</td>
              <td className="tabular py-1.5 text-right text-ink">{num(c.sent)}</td>
              <td className="tabular py-1.5 text-right text-ink">{num(c.replies)}</td>
              <td className="tabular py-1.5 text-right text-ink">{ratePct(c.replies, c.sent)}</td>
            </tr>
          ))}
          <tr>
            <td className="py-1.5 font-medium text-ink">Total</td>
            <td className="tabular py-1.5 text-right font-medium text-ink">{num(totals.contacts)}</td>
            <td className="tabular py-1.5 text-right font-medium text-ink">{num(totals.sent)}</td>
            <td className="tabular py-1.5 text-right font-medium text-ink">{num(totals.replies)}</td>
            <td className="tabular py-1.5 text-right font-medium text-ink">{ratePct(totals.replies, totals.sent)}</td>
          </tr>
        </tbody>
      </table>
    </Card>
  );
}

export function LivePanel({ clientId }: { clientId: string }) {
  const meta = clientMeta(clientId);
  if (meta?.status !== "active") {
    return (
      <Card className="p-5">
        <SectionTitle icon={<Radio size={16} />} title="Live feed" />
        <EmptyState
          title={`No live connectors — ${meta?.name ?? clientId} is non-active`}
          body="This client's view is historical. Live events stream here for active clients with connected tools."
        />
      </Card>
    );
  }
  return <LiveFeed clientId={clientId} />;
}
